//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Rinions.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_RinionsTYPE                 130
#define IDS_EDIT_MENU                   140
#define IDD_SETVIEWMODE                 310
#define IDD_SETLOGMODE                  311
#define IDD_SETNETWORK                  312
#define IDD_SETANIMATION                313
#define IDD_SETDATASAVE                 315
#define IDD_SETOUTDATA                  316
#define IDD_SETDEVICE                   317
#define IDD_FLPLAYER_PLAYER             318
#define IDD_SETSPEECH                   319
#define IDD_SETMOTION_OPENNI            320
#define IDD_SETMOTION_KINECT            321
#define IDC_CHECK_VIEW_MIRRORING        1000
#define IDC_CHECK_VIEW_USEIMAGE         1001
#define IDC_COMBO_SKL_LINE              1002
#define IDC_CHECK_LOG_POSITION          1005
#define IDC_CHECK_LOG_ROT_MATRIX        1006
#define IDC_CHECK_LOG_QUATERNION        1007
#define IDC_CHECK_LOG_ANGLE             1008
#define IDC_CHECK_LOG_NETWORK           1010
#define IDC_CHECK_LOG_NET_CHECK         1011
#define IDC_CHECK_DATA_POSITION         1015
#define IDC_CHECK_DATA_MATRIX           1016
#define IDC_CHECK_DATA_QUATERNION       1017
#define IDC_CHECK_FORCE_POSE            1018
#define IDC_INFO_CRNT_LIB               1019
#define IDC_RADIO_NET_SMEM              1020
#define IDC_CHECK_NET_LOGONLY           1021
#define IDC_RADIO_NETWORK               1022
#define IDC_CHECK_FASTNETWORK           1023
#define IDC_EDIT_SERVER_NAME            1024
#define IDC_EDIT_SERVER_PORT            1025
#define IDC_EDIT_GROUP_KEY              1026
#define IDC_EDIT_CLIENT_PORT            1027
#define IDC_EDIT_RINIONS_NAME           1028
#define IDC_CHECK_LED_CONTROL           1030
#define IDC_CHECK_MOTOR_CONTROL         1031
#define IDC_RADIO_LIB_OPENNI            1032
#define IDC_RADIO_LIB_KINECT            1033
#define IDC_RADIO_MOTION_POS            1034
#define IDC_RADIO_MOTION_ROT            1035
#define IDC_CHECK_JOINT_CONSTRAINT      1036
#define IDC_SLIDER_YROT                 1037
#define IDC_EDIT_YROT                   1038
#define IDC_SLIDER_CNFDNC               1040
#define IDC_SLIDER_SMOOTH               1041
#define IDC_SLIDER_CRRCTN               1042
#define IDC_EDIT_CNFDNC                 1043
#define IDC_EDIT_SMOOTH                 1044
#define IDC_EDIT_CRRCTN                 1045
#define IDC_CHECK_MVAV_SMOOTH           1046
#define IDC_COMBO_MVAV_TYPE             1047
#define IDC_COMBO_MVAV_NUM              1048
#define IDC_CHECK_NITE_SMOOTH           1049
#define IDC_CHECK_KINECT_SMOOTH         1050
#define IDC_COMBO_DETECT                1051
#define IDC_CHECK_FACE_DETECT           1052
#define IDC_COMBO_OUT_FPS               1060
#define IDC_CHECK_OUT_CORD              1061
#define IDC_CHECK_OUT_QUAT              1062
#define IDC_CHECK_OUT_LOGANGLE          1063
#define IDC_BUTTON_FLPLAYER_PLAY        1065
#define IDC_BUTTON_FLPLAYER_STOP        1066
#define IDC_BUTTON_FLPLAYER_PAUSE       1067
#define IDC_BUTTON_FLPLAYER_EXIT        1068
#define IDC_CHECK_AUTO_IN_FPS           1070
#define IDC_SLIDER_IN_FPS               1071
#define IDC_EDIT_IN_FPS                 1072
#define IDC_CHECK_OUT_FPS_AUTO          1073
#define IDC_SLIDER_OUT_FPS              1074
#define IDC_EDIT_OUT_FPS                1075
#define IDC_CHECK_OUT_FPS_CTRL          1077
#define IDC_CHECK_FLPLAYER_REPEAT       1080
#define IDC_CHECK_FLPLAYER_CALCQUAT     1081
#define IDC_CHECK_FLPLAYER_MIRROR       1083
#define IDC_CHECK_FLPLAYER_INITPOS      1084
#define IDC_RADIO_FLPLAYER_MT           1085
#define IDC_RADIO_FLPLAYER_CM           1086
#define IDC_RADIO_FLPLAYER_INCH         1087
#define IDC_SLIDER_FLPLAYER_TIMESCALE   1090
#define IDC_EDIT_FLPLAYER_TIMESCALE     1091
#define IDC_INFO_FLPLAYER_ALLFRAME      1092
#define IDC_INFO_FLPLAYER_ALLTIME       1093
#define IDC_INFO_FLPLAYER_FRAME         1094
#define IDC_INFO_FLPLAYER_STATE         1095
#define IDC_BUTTON_FLPLAYER_SAVE        1096
#define IDC_RADIO_SAVE_ONI              1100
#define IDC_RADIO_SAVE_ORG              1105
#define IDC_RADIO_SAVE_BVH              1106
#define IDC_RADIO_NOT_SAVE              1107
#define IDC_COMB_SAVE_BVH_FMT           1111
#define IDC_COMB_SAVE_BVH_FPS           1112
#define IDC_EDIT_SAVE_DIVTIME           1113
#define IDC_EDIT_SAVE_SZSCALE           1114
#define IDC_CHECK_SAVE_LOG_NET          1120
#define IDC_CHECK_SAVE_LOG_LCL          1121
#define IDC_EDIT_SAVE_LOG_FLDR          1123
#define IDC_BUTTON_SAVE_LOG_REFER       1124
#define IDC_EDIT_ANIMATION_UUID         1200
#define IDC_SYSLINK_RINIONS             1201
#define IDC_CHECK_SPEECH_CTRL           1210
#define IDC_SLIDER_SPEECH_CONFD         1211
#define IDC_EDIT_SPEECH_CONFD           1212
#define IDC_COMBO_SPEECH_LANG           1213
#define IDR_CALIB_TOOLBAR               1220
#define IDR_CALIB_TOOLBAR2              1221
#define IDR_DEPTH_TOOLBAR               1222
#define ID_VIEW_WND_OPEN                32000
#define ID_MODEL_WND_OPEN               32001
#define ID_DPTH_WND_OPEN                32002
#define ID_LOG_WND_OPEN                 32003
#define ID_SNSR_WND_OPEN_1              32021
#define ID_SNSR_WND_OPEN_2              32022
#define ID_SNSR_WND_OPEN_3              32023
#define ID_SNSR_WND_OPEN_4              32024
#define ID_LOAD_WND_OPEN_1              32025
#define ID_LOAD_WND_OPEN_2              32026
#define ID_LOAD_WND_OPEN_3              32027
#define ID_LOAD_WND_OPEN_4              32028
#define ID_DPTH_WND_OPEN_1              32029
#define ID_DPTH_WND_OPEN_2              32030
#define ID_DPTH_WND_OPEN_3              32031
#define ID_DPTH_WND_OPEN_4              32032
#define ID_CALIB_START                  32101
#define ID_CALIB_STOP                   32102
#define ID_CALIB_NEXT                   32103
#define ID_CALIB_DUMMY                  32104
#define ID_REC_START                    32182
#define ID_REC_STOP                     32184
#define ID_SNSR_LED                     32185
#define ID_MOTOR_UP                     32186
#define ID_MOTOR_DOWN                   32187
#define ID_MOTOR_CENTER                 32188
#define ID_DEPTH_CONTRAST               32200
#define ID_SETTING                      32780
#define ID_SETTING_VIEWMODE             32781
#define ID_SETTING_LOGINGMODE           32782
#define ID_SETTING_NETWORK              32783
#define ID_SETTING_ANIMATION            32784
#define ID_SETTING_SAVEDATA             32785
#define ID_SETTING_SPEECH               32786
#define ID_SETTING_DEVICE               32787
#define ID_SETTING_MOTION               32788
#define ID_SETTING_MOTION_OPENNI        32789
#define ID_SETTING_MOTION_KINECT        32790
#define ID_SETTING_OUTDATA              32791
#define ID_MODE_LOCAL                   32800
#define ID_MODE_NETWORK                 32801
#define ID_DUMMY                        32829
#define IDS_STR_INIT_DEVICE             57000
#define IDS_STR_RESET_DEVICE            57001
#define IDS_STR_START_SPEECH            57002
#define IDS_STR_STOP_SPEECH             57003
#define IDS_STR_RESTART_SPEECH          57004
#define IDS_STR_CREATE_IMAGE            57005
#define IDS_STR_DELETE_IMAGE            57006
#define IDS_STR_PROCSING_LOGIN          57007
#define IDS_STR_CNFRM_REBOOT            57008
#define IDS_STR_CNFRM_INIT              57009
#define IDS_STR_ERR_REBOOT              57010
#define IDS_STR_NOT_LIB32               57011
#define IDS_STR_NOT_LIB64               57012
#define IDS_STR_NOT_DEVICE              57013
#define IDS_STR_NOT_LOGIN               57014
#define IDS_STR_EXEC_MULTI              57015
#define IDS_STR_NOTOPEN_SOCKET          57016
#define IDS_STR_FAIL_RSCV               57020
#define IDS_STR_FRBDDN_SERVER           57021
#define IDS_STR_DUPLI_ANIM              57022
#define IDS_STR_ALREADY_LOGIN           57023
#define IDS_STR_NORSPNS_SERVER          57024
#define IDS_STR_NORSPNS_RELAY           57025
#define IDS_STR_SUCCESS_LOGIN           57026
#define IDS_STR_LOCAL_MODE              57027
#define IDS_STR_NETWORK_MODE            57028
#define IDS_STR_LOGGING_IN              57030
#define IDS_STR_LOGGED_OUT              57031
#define IDS_STR_RECEIVING_DATA          57032
#define IDS_STR_STATUSBAR_INIT          57033
#define IDS_STR_STATUSBAR_LCLFPS        57034
#define IDS_STR_STATUSBAR_NETFPS        57035
#define IDS_STR_STATUSBAR_NETBPS        57036
#define IDS_STR_STATUSBAR_SPEECH        57037
#define IDS_STR_SET_INVALID_UUID        57040
#define IDS_STR_REC_MODE_ONI            57041
#define IDS_STR_REC_MODE_BVH            57042
#define IDS_STR_REC_MODE_ORG            57043
#define IDS_STR_REC_MODE_ERR            57044
#define IDS_STR_MENU_WINDOW             57045
#define IDS_STR_MENU_SENSOR             57046
#define IDS_STR_NOT_READ_FACE_CSCDFL    57050
#define IDS_STR_NOT_READ_EYES_CSCDFL    57051
#define IDS_STR_NOT_READ_MOUTH_CSCDFL   57052
#define IDS_STR_NOT_LOAD_FACE_DLL       57055
#define IDS_STR_UNABLE_FACE_DETECTION   57056
#define IDS_STR_ERR_NO_SAVE_DATA        57060
#define IDS_STR_ERR_NO_LOAD_FILE        57061
#define IDS_STR_ERR_LIB_LOAD_FILE       57062
#define IDS_STR_ERR_UNKNOWN_FILE        57063
#define IDS_STR_ERR_NEXT_FRAME          57064
#define ID_APP_DATA_LOAD                58001
#define ID_APP_DATA_SAVE                58002
#define ID_APP_LOGIN                    58010
#define ID_APP_LOGOUT                   58011
#define ID_APP_DATA_RECV                58012
#define ID_APP_REBOOT                   58013
#define ID_APP_INIT                     58014

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        326
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           314
#endif
#endif
